spring:
  application:
    name: tutor-site-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tutorsite}
    username: ${DB_USER:tutor}
    password: ${DB_PASSWORD:tutor}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  admin:
    email: ${ADMIN_EMAIL:ney4s@tutorsite.local}
    password: ${ADMIN_PASSWORD:} # Замените на свой
  jwt:
    secret: ${JWT_SECRET:ddddddddddddddddddddddddddddddddddddddddddddddd} # Замените на свой 2
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}
